sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
script:
  - yarn run lint
  - yarn build
  - yarn test
after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

